# Generated by Django 3.2.2 on 2021-10-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_basicpage_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='new_tab',
            field=models.BooleanField(default=True, verbose_name='در صفحه جدید باز شود؟'),
        ),
    ]
