# Generated by Django 3.2.2 on 2021-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_link_new_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlink',
            name='app_name',
            field=models.CharField(choices=[('tax', 'tax'), ('web', 'web'), ('stock', 'stock'), ('calendar', 'calendar'), ('resume', 'resume'), ('realestate', 'realestate'), ('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('help', 'help'), ('farm', 'farm'), ('core', 'core'), ('market', 'market')], max_length=50, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='app_name',
            field=models.CharField(blank=True, choices=[('tax', 'tax'), ('web', 'web'), ('stock', 'stock'), ('calendar', 'calendar'), ('resume', 'resume'), ('realestate', 'realestate'), ('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('help', 'help'), ('farm', 'farm'), ('core', 'core'), ('market', 'market')], max_length=20, null=True, verbose_name='app_name'),
        ),
    ]
