# Generated by Django 3.2.2 on 2021-11-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0005_auto_20211106_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='is_open?'),
        ),
        migrations.AddField(
            model_name='document',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profile_documents', to='authentication.Profile', verbose_name='profiles'),
        ),
    ]
