# Generated by Django 3.2.2 on 2021-11-27 04:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\uploads2'), upload_to='core/documents', verbose_name='فایل ضمیمه'),
        ),
    ]
